site_name: CAS GLOBAL
docs_dir: docs
site_author: 'CAS GLOBAL'
site_favicon: 'favicon.ico'

pages:
  - 'CAS Technical White Paper': 'technicalwhitepaper_en.md'
  - 'CAS 技术白皮书': 'technicalwhitepaper_cn.md'
  - 'CAS Global Business White Paper': 'businesswhitepaper_en.md'
  - 'CAS Global 业务白皮书': 'businesswhitepaper_cn.md'